version: '3.9'

services:
  db:
    image: postgres
    restart: on-failure
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_NAME=${POSTGRES_NAME}
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
    ports:
      - '5432:5432'
    volumes:
      - ./.docker:/var/lib/postgresql/data
    networks:
      - api
  app:
    build: .
    container_name: nesstjs-api
    restart: on-failure
    volumes:
      - .:/usr/app
    networks:
      - api
    links:
      - db
    depends_on:
      - db

networks:
  api:
    driver: bridge
